# Generated by Django 4.2.4 on 2023-09-02 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpoutVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('channel', models.CharField(choices=[('DEV', 'Dev'), ('BETA', 'Beta'), ('STABLE', 'Stable')], max_length=128)),
            ],
        ),
    ]
